export const APP_ROUTES = {
  USER_HOME: "/home",
  LOGIN: "/login",
  SIGNUP: "/signup",
  LANDING: "/",
  PROFILE:"/profile/personal",
  PETLISTINGS:"/profile/pets",
  Vets:"/vets",
  COMMUNITY:"/community",
  ABOUT:"/about",
  MARKETPLACE:"/marketplace",
  MATCHMAKING:"/matchmaking",
  ADMIN_DASHBOARD: "/admin",
  DOCTOR_DASHBOARD: "/doctor",
};
